version: '3'
services:
  app:
    image: issue-city-monitor
    ports:
    - "8085:8085"
    depends_on:
    - mypostgres
  mypostgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=qwerty1234
     - POSTGRES_USER=localadmin
     - POSTGRES_DB=postgres