version: '3'
services:
  app:
    image: issue-city-monitor
    ports:
    - "8080:8080"
    depends_on:
    - localhost
  localhost:
    image: postgres:9.6
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=qwerty1234
     - POSTGRES_USER=localadmin
     - POSTGRES_DB=postgres